### ISSUE TITLE
project3-srs-submission

### ISSUE THREAD

**Issue by neviko** [neviko/Diff-sign-project#2]
**srs Ex3
https://github.com/neviko/Diff-sign-project/blob/master/SRS-hebrew%20new.docx

**Comment by neviko** [comment]
**srs Ex3
https://github.com/neviko/Diff-sign-project/blob/master/SRS-hebrew%20new.docx

**Comment by ItamarShDev** [comment]
broken link

**Comment by ediAm** [comment]
Sorry, we rearranged the folders and files so the link changed.
The right link : https://github.com/neviko/Diff-sign-project/blob/master/wiki_documents/Requirements/SRS-hebrew.docx
@ItamarShDev

**Comment by neviko** [comment]
done
