### ISSUE TITLE
please check Iteration 1

### ISSUE THREAD

**Issue by neviko** [neviko/Diff-sign-project#80]
hey Itamar , we already produse you Iteration 1 and now (following your request) we tagged you on That iteration .

thank you

**Comment by ItamarShDev** [comment]
[this section is empty?](https://github.com/neviko/Diff-sign-project/wiki/Iteration-1---MVP#next-iteration)

**Comment by neviko** [comment]
@ItamarShDev 
do you mean that all iteration is empty? because the link direct to Iteration 1 and it's already done

**Comment by ItamarShDev** [comment]
NVM
