### ISSUE TITLE
Design of Trivia game 

### ISSUE THREAD

**Issue by raphym** [neviko/Diff-sign-project#81]
אנחנו חייבים לשפר את העיצוב של המשחק ובנוסף הגרסה צריכה להיות מותאמת לפלפונים

אני ממליץ מבנה של דף כמו שיש בתמונה הנ"ל
![img_09062016_180606_1465484802021](https://cloud.githubusercontent.com/assets/17546494/15934842/acf13756-2e6d-11e6-9a8d-a41f4a98a7cb.jpg)

**Comment by raphym** [comment]
הבעייה העיקרית היא שלא רואים את התשובות אז עוד אופציה היא שהדף מתגלגל בצורה אוטומטית כשמופייה התשובות

**Comment by raphym** [comment]
עוד בעייה זה הזמן פסילות וניקוד שהיחס שלהם ענק ונשאר קבוע אפילו אם זה על מסך של פלאפון

**Comment by neviko** [comment]
from now on after the video is pause the page scroll to the ansers

**Comment by raphym** [comment]
זה כבר יותר טוב , כל הכבוד , נשאר לכם להתאים לפי גודל המסך
